/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.10.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Obligatto2.types";
import * as _1 from "./Obligatto2.client";
import * as _2 from "./Obligatto2.message-composer";
import * as _3 from "./Obligatto2.react-query";
import * as _4 from "./Obligatto2.recoil";
export namespace contracts {
  export const Obligatto2 = { ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
}