/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.9.2.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface Batch {
  batch_id: number;
  setoffs: [number, number][];
  [k: string]: unknown;
}
export interface DenomResponse {
  denom: string;
  [k: string]: unknown;
}
export type Addr = string;
export interface Edge {
  amount: number;
  creditor: Addr;
  debtor: Addr;
  edge_id: number;
  graph_id?: number | null;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  create_edge: {
    amount: number;
    creditor: Addr;
    [k: string]: unknown;
  };
} | {
  edit_edge: {
    amount: number;
    creditor: Addr;
    edge_id: number;
    [k: string]: unknown;
  };
} | {
  remove_edge: {
    edge_id: number;
    [k: string]: unknown;
  };
} | {
  create_graph: {
    graph: Edge[];
    [k: string]: unknown;
  };
} | {
  create_graph_simplified: {
    graph: [Addr, Addr, number][];
    graph_id: number;
    [k: string]: unknown;
  };
} | {
  edit_graph_simplified: {
    graph: [Addr, Addr, number][];
    graph_id: number;
    [k: string]: unknown;
  };
} | {
  remove_graph: {
    graph_id: number;
    [k: string]: unknown;
  };
} | {
  update_edges: {
    edges: [number, number][];
    [k: string]: unknown;
  };
} | {
  find_savings: {
    [k: string]: unknown;
  };
} | {
  find_savings_in_a_graph: {
    graph_id: number;
    [k: string]: unknown;
  };
} | {
  reset: {
    [k: string]: unknown;
  };
} | {
  save_network_to_file: {
    filepath: string;
    [k: string]: unknown;
  };
} | {
  create_graph_from_file: {
    filepath: string;
    [k: string]: unknown;
  };
} | {
  apply_set_off_from_file: {
    filepath: string;
    [k: string]: unknown;
  };
};
export interface InstantiateMsg {
  denom: string;
  [k: string]: unknown;
}
export interface Network {
  denom: string;
  owner: Addr;
  [k: string]: unknown;
}
export type QueryMsg = {
  get_denom: {
    [k: string]: unknown;
  };
} | {
  get_owner: {
    [k: string]: unknown;
  };
} | {
  all_edges: {
    [k: string]: unknown;
  };
} | {
  one_edge: {
    edge_id: number;
    [k: string]: unknown;
  };
} | {
  one_batch: {
    batch_id: number;
    [k: string]: unknown;
  };
} | {
  one_graph: {
    graph_id: number;
    [k: string]: unknown;
  };
} | {
  get_edges_by_address: {
    address: Addr;
    [k: string]: unknown;
  };
} | {
  get_edges_as_counterparty: {
    address: Addr;
    [k: string]: unknown;
  };
} | {
  get_total_debt_per_address: {
    address: Addr;
    [k: string]: unknown;
  };
} | {
  get_total_credit_per_address: {
    address: Addr;
    [k: string]: unknown;
  };
} | {
  get_total_debt_by_graph: {
    graph_id: number;
    [k: string]: unknown;
  };
} | {
  get_total_debt: {
    [k: string]: unknown;
  };
};